function preload() {
    imagemCenario = loadImage('imagens/cenario/floresta.png')
    imagemVida = loadImage('imagens/assets/coracao.png')
    imagemGameOver = loadImage('imagens/assets/game-over.png')
    imagemTelaInicial = loadImage('imagens/assets/telaInicial.png')
    fonteTelaInicial = loadFont('imagens/assets/fonteTelaInicial.otf')
    imagemPersonagem = loadImage('imagens/personagem/correndo.png')
    imagemInimigo = loadImage('imagens/inimigos/gotinha.png')
    imagemInimigoGrande = loadImage('imagens/inimigos/troll.png')
    imagemInimigoVoador = loadImage('imagens/inimigos/gotinha-voadora.png')
    fita = loadJSON('fita/fita.json')
    somDoJogo = loadSound('sons/trilhaJogo.mp3')
    somDoPulo = loadSound('sons/somPulo.mp3')
    somDaColisao = loadSound('sons/colisao.mp3')
    somGameOver = loadSound('sons/gameOver.mp3')
}